### PR TITLE
fix: return empty nodes/edges values when no connections exist.

### LINKED ISSUE #643: Internal server error occurring with relationship fields
### To reproduce
1. Create New Models A & B
2. Edit A has a B as a relationship field (1:1 or any relationship)
3. Add New A Post with an empty B field.
4. See the below graphql query result 

```
{
  As {
    edges {
      node {
        id
        Bs {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```

### Expected behavior

I don't know well the graphql spec & wpgraphql plugin in detail, but it would not return an error if an empty array is returned. (or allow a null result)

If I'm using the wrong query, please let me know.

### Screenshots
I attached my test model export, and debug log on graphql ide

[download models](https://drive.google.com/open?id=11NFgPRlCv4F6h2n8ubB9AIKPJqpZH1lr)

[download log](https://drive.google.com/open?id=11RaAlRduZQbjiOM1QAMbBLU_7yeyS63C)

### Version information
- Plugin version:
  - ACM: 0.23.0
  - Wpgraphql: 1.13.7
- WordPress version: 6.1.1
- Browser: Chrome

### Additional context

https://github.com/wpengine/atlas-content-modeler/blob/44360ffe11538525a07d7025d33063f9fd36d24e/includes/content-registration/custom-post-types-registration.php#L745-L749

For my purposes (one-to-many relationship), I just modified the line above to:
```
	// return array();
	$relationship_ids = [1]; // hello world post id 😭
```

### PR DESCRIPTION
**Pull request by mindctrl**
Closes #643

## Description

Fixes an issue where WPGraphQL would raise an "internal server error" with the text "Cannot return null for non-nullable field" when an optional relationship on a post entry has no connections to another post object.

This was introduced in changes in WPGraphQL 1.13.x.

See #643 for reproduction steps.

https://wpengine.atlassian.net/browse/MTKA-1977

## Checklist

I have:

- [x] Added an entry to CHANGELOG.md.

### CODE REVIEW

File: includes/content-registration/custom-post-types-registration.php [hunk 1]
```diff
@@ -745,7 +745,10 @@ function register_relationship_connection( array $parent_model, array $reference
 					$relationship_ids = $relationship->get_related_object_ids( $post->ID );
 
 					if ( empty( $relationship_ids ) ) {
-						return array();
+						return [
+							'edges' => [],
+							'nodes' => [],
+						];
```
Comment (mindctrl) [inline includes/content-registration/custom-post-types-registration.php:751]: Was pointed to this by Bahl as the example of how to do it https://github.com/wp-graphql/wp-graphql-woocommerce/pull/675/files#diff-e8b7026533639a0151ee8d44eb0e2c01ad90b72385082f49b8f2ed62d3edc4e4R47-R51

**Review by andrewbotz — APPROVED** [review]

**Review by rfmeier — APPROVED** [review]
